INFO     - 2019-08-20 22:57:18,843 - [__main__ main 125] Output files are saved in results/MineRLTreechop-v0/dddqn\20190820T225718.503679
INFO     - 2019-08-20 22:57:18,844 - [utils log_versions 9] 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)]
INFO     - 2019-08-20 22:57:18,956 - [utils log_versions 10] backcall==0.1.0,cached-property==1.5.1,certifi==2019.6.16,chainer==7.0.0b2,chainerrl==0.6.0,chardet==3.0.4,colorama==0.4.1,coloredlogs==10.0,cycler==0.10.0,decorator==4.4.0,filelock==3.0.12,future==0.17.1,gym==0.12.1,humanfriendly==4.18,idna==2.8,ipython==7.7.0,ipython-genutils==0.2.0,jedi==0.15.1,kiwisolver==1.1.0,lxml==4.4.1,matplotlib==3.1.1,minerl==0.2.3,numpy==1.17.0,opencv-python==4.1.0.25,parso==0.5.1,pickleshare==0.7.5,pillow==6.1.0,pip==19.2.2,prompt-toolkit==2.0.9,protobuf==3.7.1,psutil==5.6.3,pydot==1.4.1,pyglet==1.4.2,Pygments==2.4.2,pyparsing==2.4.2,pyreadline==2.1,Pyro4==4.76,python-dateutil==2.8.0,requests==2.22.0,scipy==1.3.1,serpent==1.28,setuptools==41.0.1,six==1.12.0,tqdm==4.34.0,traitlets==4.3.2,typing==3.6.6,typing-extensions==3.6.6,urllib3==1.25.3,wcwidth==0.1.7,wheel==0.33.4,wincertstore==0.2
INFO     - 2019-08-20 22:57:18,957 - [__main__ _main 137] The first `gym.make(MineRL*)` may take several minutes. Be patient!
INFO     - 2019-08-20 22:57:43,157 - [minerl.env.malmo.instance.5c68a9 _launch_minecraft 635] Starting Minecraft process: ['C:\\Users\\danie\\AppData\\Local\\Temp\\tmpj2occ9bh\\Minecraft\\launchClient.bat', '-port', '9001', '-env', '-runDir', 'C:\\Users\\danie\\AppData\\Local\\Temp\\tmpj2occ9bh\\Minecraft\\run']
INFO     - 2019-08-20 22:57:43,279 - [minerl.env.malmo.instance.5c68a9 _launch_process_watcher 658] Starting process watcher for process 404 @ localhost:9001
ERROR    - 2019-08-20 22:57:44,897 - [minerl.env.malmo.instance.5c68a9 launch 474] 
ERROR    - 2019-08-20 22:57:44,897 - [minerl.env.malmo.instance.5c68a9 launch 474] FAILURE: Build failed with an exception.
ERROR    - 2019-08-20 22:57:44,897 - [minerl.env.malmo.instance.5c68a9 launch 474] 
ERROR    - 2019-08-20 22:57:44,898 - [minerl.env.malmo.instance.5c68a9 launch 474] * What went wrong:
ERROR    - 2019-08-20 22:57:44,898 - [minerl.env.malmo.instance.5c68a9 launch 474] Could not determine java version from '12.0.2'.
ERROR    - 2019-08-20 22:57:44,898 - [minerl.env.malmo.instance.5c68a9 launch 474] 
ERROR    - 2019-08-20 22:57:44,898 - [minerl.env.malmo.instance.5c68a9 launch 474] * Try:
ERROR    - 2019-08-20 22:57:44,899 - [minerl.env.malmo.instance.5c68a9 launch 474] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
ERROR    - 2019-08-20 22:57:44,899 - [__main__ main 132] execution failed.
Traceback (most recent call last):
  File "dqn_family.py", line 130, in main
    _main(args)
  File "dqn_family.py", line 192, in _main
    core_env = gym.make(args.env)
  File "D:\Users\danie\Anaconda3\envs\mine\lib\site-packages\gym-0.12.1-py3.7.egg\gym\envs\registration.py", line 183, in make
    return registry.make(id, **kwargs)
  File "D:\Users\danie\Anaconda3\envs\mine\lib\site-packages\gym-0.12.1-py3.7.egg\gym\envs\registration.py", line 125, in make
    env = spec.make(**kwargs)
  File "D:\Users\danie\Anaconda3\envs\mine\lib\site-packages\gym-0.12.1-py3.7.egg\gym\envs\registration.py", line 89, in make
    env = cls(**_kwargs)
  File "D:\Users\danie\Anaconda3\envs\mine\lib\site-packages\minerl\env\core.py", line 133, in __init__
    self.instance = self._get_new_instance(port)
  File "D:\Users\danie\Anaconda3\envs\mine\lib\site-packages\minerl\env\core.py", line 155, in _get_new_instance
    instance.launch()
  File "D:\Users\danie\Anaconda3\envs\mine\lib\site-packages\minerl\env\malmo.py", line 477, in launch
    raise EOFError(error_str + "\n\nMinecraft process finished unexpectedly. There was an error with Malmo.")
EOFError: 
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine java version from '12.0.2'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.


Minecraft process finished unexpectedly. There was an error with Malmo.
